/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleConsultingRouteImport } from './routes/$locale/consulting'
import { Route as LocaleMediaKitRouteImport } from './routes/$locale/media-kit'
import { Route as LocaleMediaIndexRouteImport } from './routes/$locale/media/index'
import { Route as LocaleMediaSlugRouteImport } from './routes/$locale/media/$slug'
import { Route as LocaleResearchIndexRouteImport } from './routes/$locale/research/index'
import { Route as LocaleResearchSlugRouteImport } from './routes/$locale/research/$slug'
import { Route as ApiHelgaAuthorizeRouteImport } from './routes/api/helga/authorize'
import { Route as ApiHelgaListenRouteImport } from './routes/api/helga/listen'
import { Route as ApiHelgaRecordingRouteImport } from './routes/api/helga/recording'
import { Route as ApiHelgaWebhookRouteImport } from './routes/api/helga/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleConsultingRoute = LocaleConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleMediaKitRoute = LocaleMediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleMediaIndexRoute = LocaleMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleMediaSlugRoute = LocaleMediaSlugRouteImport.update({
  id: '/media/$slug',
  path: '/media/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleResearchIndexRoute = LocaleResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleResearchSlugRoute = LocaleResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiHelgaAuthorizeRoute = ApiHelgaAuthorizeRouteImport.update({
  id: '/api/helga/authorize',
  path: '/api/helga/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelgaListenRoute = ApiHelgaListenRouteImport.update({
  id: '/api/helga/listen',
  path: '/api/helga/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelgaRecordingRoute = ApiHelgaRecordingRouteImport.update({
  id: '/api/helga/recording',
  path: '/api/helga/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelgaWebhookRoute = ApiHelgaWebhookRouteImport.update({
  id: '/api/helga/webhook',
  path: '/api/helga/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/consulting': typeof LocaleConsultingRoute
  '/$locale/media-kit': typeof LocaleMediaKitRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/media/$slug': typeof LocaleMediaSlugRoute
  '/$locale/research/$slug': typeof LocaleResearchSlugRoute
  '/api/helga/authorize': typeof ApiHelgaAuthorizeRoute
  '/api/helga/listen': typeof ApiHelgaListenRoute
  '/api/helga/recording': typeof ApiHelgaRecordingRoute
  '/api/helga/webhook': typeof ApiHelgaWebhookRoute
  '/$locale/media/': typeof LocaleMediaIndexRoute
  '/$locale/research/': typeof LocaleResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/consulting': typeof LocaleConsultingRoute
  '/$locale/media-kit': typeof LocaleMediaKitRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/media/$slug': typeof LocaleMediaSlugRoute
  '/$locale/research/$slug': typeof LocaleResearchSlugRoute
  '/api/helga/authorize': typeof ApiHelgaAuthorizeRoute
  '/api/helga/listen': typeof ApiHelgaListenRoute
  '/api/helga/recording': typeof ApiHelgaRecordingRoute
  '/api/helga/webhook': typeof ApiHelgaWebhookRoute
  '/$locale/media': typeof LocaleMediaIndexRoute
  '/$locale/research': typeof LocaleResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/consulting': typeof LocaleConsultingRoute
  '/$locale/media-kit': typeof LocaleMediaKitRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/media/$slug': typeof LocaleMediaSlugRoute
  '/$locale/research/$slug': typeof LocaleResearchSlugRoute
  '/api/helga/authorize': typeof ApiHelgaAuthorizeRoute
  '/api/helga/listen': typeof ApiHelgaListenRoute
  '/api/helga/recording': typeof ApiHelgaRecordingRoute
  '/api/helga/webhook': typeof ApiHelgaWebhookRoute
  '/$locale/media/': typeof LocaleMediaIndexRoute
  '/$locale/research/': typeof LocaleResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/consulting'
    | '/$locale/media-kit'
    | '/$locale/'
    | '/$locale/media/$slug'
    | '/$locale/research/$slug'
    | '/api/helga/authorize'
    | '/api/helga/listen'
    | '/api/helga/recording'
    | '/api/helga/webhook'
    | '/$locale/media/'
    | '/$locale/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale/consulting'
    | '/$locale/media-kit'
    | '/$locale'
    | '/$locale/media/$slug'
    | '/$locale/research/$slug'
    | '/api/helga/authorize'
    | '/api/helga/listen'
    | '/api/helga/recording'
    | '/api/helga/webhook'
    | '/$locale/media'
    | '/$locale/research'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/consulting'
    | '/$locale/media-kit'
    | '/$locale/'
    | '/$locale/media/$slug'
    | '/$locale/research/$slug'
    | '/api/helga/authorize'
    | '/api/helga/listen'
    | '/api/helga/recording'
    | '/api/helga/webhook'
    | '/$locale/media/'
    | '/$locale/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  ApiHelgaAuthorizeRoute: typeof ApiHelgaAuthorizeRoute
  ApiHelgaListenRoute: typeof ApiHelgaListenRoute
  ApiHelgaRecordingRoute: typeof ApiHelgaRecordingRoute
  ApiHelgaWebhookRoute: typeof ApiHelgaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/consulting': {
      id: '/$locale/consulting'
      path: '/consulting'
      fullPath: '/$locale/consulting'
      preLoaderRoute: typeof LocaleConsultingRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/media-kit': {
      id: '/$locale/media-kit'
      path: '/media-kit'
      fullPath: '/$locale/media-kit'
      preLoaderRoute: typeof LocaleMediaKitRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/media/': {
      id: '/$locale/media/'
      path: '/media'
      fullPath: '/$locale/media/'
      preLoaderRoute: typeof LocaleMediaIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/media/$slug': {
      id: '/$locale/media/$slug'
      path: '/media/$slug'
      fullPath: '/$locale/media/$slug'
      preLoaderRoute: typeof LocaleMediaSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/research/': {
      id: '/$locale/research/'
      path: '/research'
      fullPath: '/$locale/research/'
      preLoaderRoute: typeof LocaleResearchIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/research/$slug': {
      id: '/$locale/research/$slug'
      path: '/research/$slug'
      fullPath: '/$locale/research/$slug'
      preLoaderRoute: typeof LocaleResearchSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/helga/authorize': {
      id: '/api/helga/authorize'
      path: '/api/helga/authorize'
      fullPath: '/api/helga/authorize'
      preLoaderRoute: typeof ApiHelgaAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/helga/listen': {
      id: '/api/helga/listen'
      path: '/api/helga/listen'
      fullPath: '/api/helga/listen'
      preLoaderRoute: typeof ApiHelgaListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/helga/recording': {
      id: '/api/helga/recording'
      path: '/api/helga/recording'
      fullPath: '/api/helga/recording'
      preLoaderRoute: typeof ApiHelgaRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/helga/webhook': {
      id: '/api/helga/webhook'
      path: '/api/helga/webhook'
      fullPath: '/api/helga/webhook'
      preLoaderRoute: typeof ApiHelgaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleConsultingRoute: typeof LocaleConsultingRoute
  LocaleMediaKitRoute: typeof LocaleMediaKitRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleMediaSlugRoute: typeof LocaleMediaSlugRoute
  LocaleResearchSlugRoute: typeof LocaleResearchSlugRoute
  LocaleMediaIndexRoute: typeof LocaleMediaIndexRoute
  LocaleResearchIndexRoute: typeof LocaleResearchIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleConsultingRoute: LocaleConsultingRoute,
  LocaleMediaKitRoute: LocaleMediaKitRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleMediaSlugRoute: LocaleMediaSlugRoute,
  LocaleResearchSlugRoute: LocaleResearchSlugRoute,
  LocaleMediaIndexRoute: LocaleMediaIndexRoute,
  LocaleResearchIndexRoute: LocaleResearchIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  ApiHelgaAuthorizeRoute: ApiHelgaAuthorizeRoute,
  ApiHelgaListenRoute: ApiHelgaListenRoute,
  ApiHelgaRecordingRoute: ApiHelgaRecordingRoute,
  ApiHelgaWebhookRoute: ApiHelgaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
